/********************************************************************************
This code is automatically generated by the MotePy compiler. DO NOT EDIT!
********************************************************************************/
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <stdlib.h>
/*Managed memory variables*/
uint32_t __vtmem[3720];
float (*stage1_vec2_p)[60]= (float (*)[60]) &__vtmem[0];
#define stage1_vec2 (*stage1_vec2_p)
float (*stage1_weights_p)[60][60]= (float (*)[60][60]) &__vtmem[60];
#define stage1_weights (*stage1_weights_p)
float (*stage1_vec1_p)[60]= (float (*)[60]) &__vtmem[3660];
#define stage1_vec1 (*stage1_vec1_p)
/*End of managed memory variables*/
/*Module vars for stage1*/
/*End of module vars for stage1*/
typedef enum { __stage1_process}  __pipeline;
 __pipeline __state = __stage1_process;
void _stage1_init()
{
    {
    }
}
void _stage1_process()
{
    float __t0;
    {
        for(int __i=0; __i<60; __i++)
        {
            stage1_vec1[__i]=1;
            stage1_vec1[__i]=(stage1_vec1[__i]+stage1_vec2[__i]);
            __t0=0;
            for(int __j=0; __j<60; __j++)
            {
                __t0=((stage1_vec1[__j]*stage1_weights[__j][__i])+__t0);
            }
            stage1_vec1[__i]=(__t0+stage1_vec1[__i]);
        }
    }
}
void loop()
{
    switch(__state)
    {
        case __stage1_process:
        __state = __stage1_process;
        _stage1_process();
        break;
        default :
        __state = __stage1_process;
    }
}
void setup()
{
    _stage1_init();
}