/********************************************************************************
This code is automatically generated by the VerticalThings compiler. DO NOT EDIT!
********************************************************************************/
#include <stdio.h>
#include <stdint.h>
/*Managed memory variables*/
uint32_t __vtmem[30];
float (*init_res_p)[20]= (float (*)[20]) &__vtmem[0];
#define init_res (*init_res_p)
float (*init2_res2_p)[30]= (float (*)[30]) &__vtmem[0];
#define init2_res2 (*init2_res2_p)
/*End of managed memory variables*/
/*Module vars for init*/
/*End of module vars for init*/
/*Module vars for init2*/
float (*init2_res3_p)[30]= (float (*)[30]) ((void *) 100);
#define init2_res3 (*init2_res3_p)
/*End of module vars for init2*/
typedef enum { __init_init, __init2_init}  __pipeline;
 __pipeline __state = __init_init;
void _init_init()
{
    {
        for(int __i=0; __i<20; __i++)
        {
            init_res[__i]=0;
            init_res[__i]=(init_res[__i]+init_res[__i]);
        }
        __state = __init2_init;
    }
}
void _init2_init()
{
    {
        init2_res3[0]=0;
        for(int __i=0; __i<30; __i++)
        {
            init2_res2[__i]=0;
            init2_res2[__i]=(init2_res2[__i]+init2_res2[__i]);
        }
        init2_res3[0]=(init2_res3[0]+1);
    }
}
void loop()
{
    switch(__state)
    {
        case __init_init:
        __state = __init_init;
        _init_init();
        break;
        case __init2_init:
        __state = __init_init;
        _init2_init();
        break;
        default :
        __state = __init_init;
    }
}
void setup()
{
    _init_init();
    _init2_init();
}